---
title: Kaggle
---

[Kaggle](https://www.kaggle.com) is the world's largest data science community. One of Kaggle's features is "Notebooks", which is "*a cloud computational environment that enables reproducible and collaborative analysis*". In particular, Kaggle provides access to GPUs for free. Every lesson provides direct links to notebooks on Kaggle that are ready for you to start using. Click "**Copy & Edit**" at the top right of any notebook to start working with it.

**In order to use a GPU on Kaggle, your account must be phone verified. You can enable this on [your account page](https://www.kaggle.com/me/account) (after you've signed up and are logged in) under "Phone Verification".**

Here's some information from Kaggle's notebook page:

> Jupyter notebooks consist of a sequence of cells, where each cell is formatted in either Markdown (for writing text) or in a programming language of your choice (for writing code). To start a notebook, click on “Create Notebook”, and select “Notebook”. This will open the Notebooks editing interface.
>
>"[Comprehensive data exploration with Python](https://www.kaggle.com/code/pmarcelino/comprehensive-data-exploration-with-python/notebook)" is a great example of a Python Jupyter Notebook-type.

Instead of Kaggle, you can also use Paperspace Gradient. We've found they work really well for this course, and have good free options. If you don't have a Paperspace account yet, sign up with [this link](https://console.paperspace.com/signup?R=lg6rnx) to get $10 credit -- and we get a credit too. Gradient is a little harder to use because the notebooks are not ready-to-run, but it's more powerful because you get a full Linux environment to work in. It's a good option for folks who are comfortable working with git and the command line. To access the course notebooks on Paperspace, you will need to clone [this GitHub repo](https://github.com/fastai/course22).
